version: '3.8'

services:
  database:
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=YOUR_PASSWORD
      - POSTGRES_USER=YOUR_USERNAME
      - POSTGRES_DB=YOUR_DATABASE
  
  api:
    build: .
    ports:
      - 3000:3000
      - 5000:5000
    expose:
      - 3000
      - 5000
    volumes:
      - ./node_modules:/node_modules:ro
      - .:/app